name: mecho
description: A unified Flutter project (Customer + Mechanic)

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0

  # 🔹 Firebase
  firebase_core: ^3.15.1
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.1.4
  firebase_analytics: ^11.2.1

  # 🔹 Notifications
  flutter_local_notifications: ^17.2.1 # ✅ Android/iOS only

  # 🔹 Fonts & Audio
  google_fonts: ^6.1.0
  just_audio: ^0.9.38
  geolocator: ^14.0.2
  geocoding: ^2.2.0

  # 🔹 Storage / Preferences
  shared_preferences: ^2.2.2

  # 🔹 File handling
  image_picker: ^1.1.2
  file_selector: ^0.9.0
  file_picker: ^8.0.0
  open_filex: ^4.6.0
  path_provider: ^2.1.5
  path: ^1.9.0
  location: ^6.0.2
  pinput: ^5.0.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illu-2.png
    - assets/illu-1.png
    - assets/google.png
    - assets/mecho.jpg
    - assets/bike.png
    - assets/car.png
    - assets/car.jpg
    - assets/logoc.png
    - assets/circle.png
    - assets/shop.jpg
    - assets/illu-3.png
    - assets/ill-1.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/mecho.jpg"
